### PR TITLE
ci: cap gentx amount

### PR DESCRIPTION
**Pull request by boz**
@anilCSE @jackzampolin

### CODE REVIEW

**Comment by anilCSE** [comment]
Thanks @boz .
One concern I have is we should ask everyone to update their repos with `ovrclk/net:master` if we want to validate their PRs via  `CI`. Another way is, we can just merge all these PRs and run the check in a `loop`

We can merge this anyway as it helps future PRs to be valid.

**Review by anilCSE — APPROVED** [review]

**Comment by boz** [comment]
@anilCSE no problem we can just run it against all the gentxs before we merge them.

```sh
for file in akashnet-1/gentxs/*.json; do
  ./scripts/check-gentx-amount.sh "$file"
done
```

btw I made a mistake when modifying the check script, it'll never fail anyways :joy:

**Comment by anilCSE** [comment]
Oops, I only tested it against my PR and merged! Thanks @boz

**Comment by boz** [comment]
@anilCSE I totally misread your comment and said the same thing you did :joy: 

Feel free to take it out of the check if you think it's better that way.

**Pull request merged**
