### PR TITLE
Added gentx for FreeFlix Media

### PR DESCRIPTION
**Pull request by sprprashanth1443**

### CODE REVIEW

**Comment by sprprashanth1443** [comment]
Hello, My gentx verification failed. May I know the reason?

**Comment by anilCSE** [comment]
> Hello, My gentx verification failed. May I know the reason?

Please avoid `whitespace` in the filename. Just renaming it should fix the issue

**Comment by sprprashanth1443** [comment]
> > Hello, My gentx verification failed. May I know the reason?
> 
> Please avoid `whitespace` in the filename. Just renaming it should fix the issue

Sure ..will try again and let you know.

**Comment by anilCSE** [comment]
Looks like your account address is not in genesis. Can you cross check if your validator operator address is same as the one you submitted for KYC/testnet rewards?

**Comment by sprprashanth1443** [comment]
> Looks like your account address is not in genesis. Can you cross check if your validator operator address is same as the one you submitted for KYC/testnet rewards?

Sure, thanks.

**Comment by sprprashanth1443** [comment]
Wrong PR

**Pull request closed without merging**
