### PR TITLE
testnet network support - 3biwy2ymjnknb - validator,rpc,api

### PR DESCRIPTION
**Pull request by Chainode**

### CODE REVIEW

**Comment by akhilkumarpilli** [comment]
@Chainode , Your Moniker and validator addresses are required, please update the PR with those details

**Comment by Chainode** [comment]
@akhilkumarpilli Sure but first is this still relevant? See https://github.com/ovrclk/ecosystem/issues/683?

**Comment by akhilkumarpilli** [comment]
We are just linking moniker, validator address with participation code.  That's the reason, we are asking everyone to share validator details.

**Comment by Chainode** [comment]
Moniker: ChainodeTech; Validator address: akashvaloper1glj3c4mln8dzvf68qt7l7k57ky73ccplhdsa4h

**Pull request closed without merging**
