### PR TITLE
Added load balancer

### PR DESCRIPTION
**Pull request by c29r3**
Due to uneven load on RPC \ API, I added a load balancer

### CODE REVIEW

**Comment by arno01** [comment]
it breaks the client:

```
$ akash --node "https://akash.c29r3.xyz:443/api" status
Error: wrong ID: no ID
```

**Comment by c29r3** [comment]
> it is missing the port and it breaks the client:
> 
> ## no port
> ```
> $ akash --node "https://akash.c29r3.xyz/api" status
> Error: post failed: Post "https://akash.c29r3.xyz/api": dial tcp: address akash.c29r3.xyz: missing port in address
> ```
> 
> ## with the port
> ```
> $ akash --node "https://akash.c29r3.xyz:443/api" status
> Error: wrong ID: no ID
> ```

RPC != API. 
```
akash --node "https://akash.c29r3.xyz:443/rpc" status
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"3b623841a46e7c3fa464dc3d5891d288aa398983","listen_addr":"tcp://0.0.0.0:28956","network":"akashnet-2","version":"","channels":"40202122233038606100","moniker":"akash-snapshots","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:28957"}},"SyncInfo":{"latest_block_hash":"9EBE4EF1D7CACE67E5E82A418AC0F302CE21500994A011379916899F1BD3FD7A","latest_app_hash":"E5002F3A4991C63D848FEBC52DE643A8B8B62C3EEB468D5B2C50CE730D5C1058","latest_block_height":"4304906","latest_block_time":"2022-01-15T16:15:05.206460889Z","earliest_block_hash":"5D4EC5B544F44BCC167DBF72EBE94AB4EDA3F71BCE71470DCD281D3F1338A64A","earliest_app_hash":"1451C7AB8F669C9D5E35CD45F12C9C7610F64C878ECE70AF640199D5BE85BA9A","earliest_block_height":"4085501","earliest_block_time":"2021-12-30T02:03:21.352166305Z","catching_up":false},"ValidatorInfo":{"Address":"4BDAE15710A3F8E8CA98E89322C05A43D2A3A358","PubKey":{"type":"tendermint/PubKeyEd25519","value":"6TVija7mFrzGGJxGVAJmUvwLRN6FqF7i6MX/ogNFENo="},"VotingPower":"0"}}
```

**Comment by arno01** [comment]
dang! I was blind :man_facepalming: 

LGTM

**Comment by boz** [comment]
Thanks @c29r3 @arno01!

**Pull request merged**
