### PR TITLE
Update rpc-nodes.txt

### PR DESCRIPTION
**Pull request by lightiv**

### CODE REVIEW

**Review by dmikey — APPROVED** [review]

**Comment by dmikey** [comment]
@lightiv can you give us some more information around the node itself?

**Comment by lightiv** [comment]
This node specs are:

VPS Node

2 CPU
8 MB RAM
320 GB Hard Drive

Note I updated the url: 

http://akash-sentry01.skynetvalidators.com:26657

**Comment by dmikey** [comment]
@lightiv 8GB ram I'm guessing?

**Comment by dmikey** [comment]
haven't heard back, feel free to reopen this if it's still a goal paul.

**Comment by lightiv** [comment]
Hi, I did not respond because I though it was a give that I meant 8 GB instead of 8 MBs.  I don't have the re-open button so I will resubmit a new Pull request.

**Pull request closed without merging**
