### PR TITLE
testnet network support - 7osk3k2mvww7vmg- validator,rpc,api

### PR DESCRIPTION
**Pull request by bitoven-dev**

### CODE REVIEW

**Comment by akhilkumarpilli** [comment]
@bitoven-dev , Your Moniker and validator addresses are required, please update the PR with those details

**Comment by bitoven-dev** [comment]
And where to put it? The docs and sample file didn't mention it https://docs.akash.network/testnet-challenges/testnet-challenges/network-support#submission and https://github.com/ovrclk/net/blob/master/edgenet/seed-nodes.txt

**Comment by akhilkumarpilli** [comment]
@bitoven-dev , You can update your validator details here as a comment. We are just linking validator with participation code. That's the reason, we are asking your validator details.

**Comment by bitoven-dev** [comment]
I see
Moniker: Bitoven
Validator address: akashvaloper18gf5k74wfwg557umtda6yq6qwjava8f5xc44ss

**Pull request closed without merging**
