### PR TITLE
testnet network support - 24w1nsuqt345fb6 - validator,rpc,api

### PR DESCRIPTION
**Pull request by hitexmax**

### CODE REVIEW

**Comment by PrathyushaLakkireddy** [comment]
@hitexmax, Your Moniker and validator addresses are required, please update the PR with those details.

**Comment by hitexmax** [comment]
> @hitexmax, Your Moniker and validator addresses are required, please update the PR with those details.

For what purposes you collect this data and when is the deadline? please explain

**Comment by PrathyushaLakkireddy** [comment]
> > @hitexmax, Your Moniker and validator addresses are required, please update the PR with those details.
> 
> For what purposes you collect this data and when is the deadline? please explain



> > @hitexmax, Your Moniker and validator addresses are required, please update the PR with those details.
> 
> For what purposes you collect this data and when is the deadline? please explain


@hitexmax, We are just linking validator with participation code. That's the reason, we are asking your validator details. Please update the details as comment ASAP.

**Comment by hitexmax** [comment]
> @hitexmax, Your Moniker and validator addresses are required, please update the PR with those details.

Moniker hitexmax
Operator Address akashvaloper1x6h570re8d87cyuelrchkkym2de68tysndxaex

**Pull request closed without merging**
